/**
 * Convex API references for the driver app.
 * Maps to packages/backend/convex/ function modules.
 *
 * The backend uses @convex-dev/auth and these function paths:
 *   - drivers.myProfile, drivers.updateStatus, drivers.getEarnings
 *   - rides.acceptRequest, rides.rejectRequest, rides.startRide, rides.completeRide, rides.myActiveRide, rides.myHistory
 *   - matching.myPendingRequests
 *   - locations.updateDriverLocation
 *   - vehicles.register, vehicles.myVehicles, vehicles.update
 *   - qr.myQrCode
 *
 * We reference these via the api object generated by Convex.
 * Until codegen runs, we use string references with `api` from convex/_generated/api.
 */

// Re-export for convenience — these are used in useQuery/useMutation calls
// with string function references like api.drivers.myProfile
export const API = {
  drivers: {
    myProfile: "drivers:myProfile" as any,
    updateStatus: "drivers:updateStatus" as any,
    getEarnings: "drivers:getEarnings" as any,
  },
  rides: {
    acceptRequest: "rides:acceptRequest" as any,
    rejectRequest: "rides:rejectRequest" as any,
    startRide: "rides:startRide" as any,
    completeRide: "rides:completeRide" as any,
    cancelRide: "rides:cancelRide" as any,
    myActiveRide: "rides:myActiveRide" as any,
    myHistory: "rides:myHistory" as any,
    getById: "rides:getById" as any,
  },
  matching: {
    myPendingRequests: "matching:myPendingRequests" as any,
  },
  locations: {
    updateDriverLocation: "locations:updateDriverLocation" as any,
  },
  vehicles: {
    register: "vehicles:register" as any,
    myVehicles: "vehicles:myVehicles" as any,
    update: "vehicles:update" as any,
  },
  qr: {
    myQrCode: "qr:myQrCode" as any,
  },
} as const;
